#!/bin/bash

#functions/methods 
#functions are intended to complete specific task, it takes input and does the job 

USERID=$(id -u)

    if [ $USERID -ne 0 ]; then 
        echo "please run this script with root user access" 
        exit 1
    fi 

VALIDATE(){
    if [ $1 -ne 0 ]; then 
        echo "$2 .... faliure"
    else 
        echo "$2 .... sucess"
    fi
}
dnf install nginx -y 
VALIDATE $? "installing nginx"

dnf install mysql -y 
VALIDATE $? "installing mysql"

dnf install nodejs -y 
VALIDATE $? "installing nodejs"